#!/bin/sh
ssh -i ~/.ssh/id_rsa ubuntu@172.31.92.27 <<EOF

    cd ~/dist
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v10.11.0
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    sudo cp -a /home/ubuntu/dist/. /var/www/html/

    exit
EOF